### ISSUE TITLE
merge highlightrecovery branch into master

### ISSUE THREAD

**Issue by heckflosse** [CarVac/filmulator-gui#106]
would make sense imho

**Comment by heckflosse** [comment]
@CarVac Any thoughts?

**Comment by CarVac** [comment]
I wanted to get automated Windows builds working and maybe an installer first. This weekend is a holiday so maybe I'll try it then.

**Comment by gaaned92** [comment]
@CarVac  Some news?
When you speak of an installer, do you think of something like windowsInnoSetup ? I prefer that to NSIS as it seems to me much faster: when building Darktable, the NSIS step is very very  long.

**Comment by CarVac** [comment]
I'm gonna try Inno Setup. I'm working on getting it working with CI.

**Comment by gaaned92** [comment]
If you use Travis CI, I think @aferrero2707 can help

**Comment by CarVac** [comment]
I'm on the verge of having it working with Azure Pipelines.

**Comment by heckflosse** [comment]
@CarVac 
> I'm on the verge of having it working with Azure Pipelines.

Whatever you use, if it leads to a smart way to install filmulator, it will be an improvement :+1:

**Comment by CarVac** [comment]
Already done.

https://discuss.pixls.us/t/filmulator-nightly-builds/12838?u=carvac

**Comment by heckflosse** [comment]
Maybe also worth to mention that the new version got a lot improvements (speedup, less memory usage) and uses librtprocess

**Comment by CarVac** [comment]
The nightly builds have had those changes for a while.

**Comment by CarVac** [comment]
I'm going to try to do a release this weekend.
