### ISSUE TITLE
Minimum window width is too wide for 13" Macbook

### ISSUE THREAD

**Issue by dconrad5** [CarVac/filmulator-gui#111]
At UI Scale 1, the minimum window width is too wide to fit on a 13" Macbook, see pic:

<img width="1280" alt="Screen Shot 2020-05-25 at 12 07 59 PM" src="https://user-images.githubusercontent.com/988677/83095648-6d100c80-a069-11ea-8cb4-e877e27f3cb6.png">

**Comment by CarVac** [comment]
I will have to experiment to see if I can make Filmulator detect the monitor size and reduce the default scale on first launch.

**Comment by CarVac** [comment]
Instead of doing anything complicated, I reduced the minimum window size from 1366 pixels to 1200, with small UI tweaks to text that would be covered up by the lens correction input box.

ac9b306

Can you see if it launches in a size that fits with UI Scale 1? I'm not sure about the behavior.

**Comment by dconrad5** [comment]
Here's some screenshots of the default window size when it launches at UI Scale 1, it just ends up the full size of the screen:

<img width="1280" alt="Screen Shot 2020-06-17 at 10 26 25 PM" src="https://user-images.githubusercontent.com/988677/84975127-4aae6380-b0ea-11ea-838b-e66660f4a07f.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 26 45 PM" src="https://user-images.githubusercontent.com/988677/84975131-4d10bd80-b0ea-11ea-8e42-8f64d6633428.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 26 54 PM" src="https://user-images.githubusercontent.com/988677/84975132-4da95400-b0ea-11ea-8e31-da69decb0b3c.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 27 00 PM" src="https://user-images.githubusercontent.com/988677/84975137-500bae00-b0ea-11ea-9904-2a0067ec4dd3.png">


And here it is at minimum window width, UI Scale 1:

<img width="1280" alt="Screen Shot 2020-06-17 at 10 27 47 PM" src="https://user-images.githubusercontent.com/988677/84975194-6a458c00-b0ea-11ea-9e9a-4858694c5032.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 27 42 PM" src="https://user-images.githubusercontent.com/988677/84975197-6b76b900-b0ea-11ea-9868-7b3f6eaec571.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 27 33 PM" src="https://user-images.githubusercontent.com/988677/84975199-6b76b900-b0ea-11ea-9b8e-571d4358663c.png">
<img width="1280" alt="Screen Shot 2020-06-17 at 10 27 54 PM" src="https://user-images.githubusercontent.com/988677/84975202-6b76b900-b0ea-11ea-90d6-7884198eb45f.png">

Looks good to me! I can check/screenshot any other tweaks you want to make though.

**Comment by CarVac** [comment]
That's probably all I'll do for now. Eventually I may try to have it remember the previous window size, but that's for later on down the road.
