### ISSUE TITLE
Req: Open files (or folders) directly rather than import into database

### ISSUE THREAD

**Issue by xiota** [CarVac/filmulator-gui#118]
Would be nice to be able to call the program with a filename and have it opened for processing without having to go through the extra step of importing.

**Comment by CarVac** [comment]
That feature already exists in the Nightly Builds.

https://discuss.pixls.us/t/filmulator-nightly-builds-now-for-windows-and-linux/12838

Call filmulator with one filename as an argument; it'll automatically import, enqueue, and load it on startup.

**Comment by xiota** [comment]
Thanks... I was just trying out the AppImage from the GitHub Releases.
