### ISSUE TITLE
Req: Store thumbnails in ~/.cache instead of ~/.local/share

### ISSUE THREAD

**Issue by xiota** [CarVac/filmulator-gui#121]
Saw this message in the terminal:

    Thumbnail being written to: /home/xiota/.local/share/filmulator/thumbs/a354/a3541463202c7001c901965128454ac40001

Would be nice if thumbnails were stored in `~/.cache` instead of `~/.local/share`.

**Comment by CarVac** [comment]
Any reason in particular?

**Comment by xiota** [comment]
The purpose of the cache directory is to store nonessential data.  It's where other programs store thumbnails.  There's already a `~/.cache/Filmulator`.  It's nice to have a single place to check for left over cruft.

There's also already a `~/.config/Filmulator` that the database could be moved to.

**Comment by CarVac** [comment]
It's not nonessential, you'll have no idea what the photos are if you don't have the thumbnails.

**Comment by xiota** [comment]
Okay... well... I'm clearing out filmulator-gui since it doesn't really work well on my system... and any idea why `/usr/lib/filmulator-gui`was created?  I only ever ran the AppImage files.  It shouldn't have had permissions needed to be able to write there.

**Comment by CarVac** [comment]
I don't know. I'll have to look into it.

**Comment by xiota** [comment]
It contained qml related files... so probably Qt's fault.  I ran the 0.9.1 nightly appimage after removing the folder, and it wasn't recreated.
