### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by hfiguiere** [CarVac/filmulator-gui#126]
Hi,

I submitted filmulator to Flathub to install it as a flatpak package (Linux, currently x86_64).

  https://github.com/flathub/flathub/pull/2012

When it gets merged, it would be awesome if you could list it on the Downloads page for Filmulator.
We can also give you access to the repository so you can, *if you wish* update the flatpak when there is a new release.

I will submit separately patches needed for Flathub / Freedesktop compliance.

Thanks

**Comment by CarVac** [comment]
I left a comment in your fork, but you should probably make it so that you use CMake instead of qmake, since Qt itself is heading away from qmake.

**Comment by anarcat** [comment]
i think this ticket can be closed
