### ISSUE TITLE
Desktop file invalid

### ISSUE THREAD

**Issue by hfiguiere** [CarVac/filmulator-gui#129]
This exec line in the desktop file is:

```
Exec=cd/usr/lib/filmulator-gui && /usr/lib/filmulator-gui/filmulator-gui
```
Many problems:

- `cd` is missing a space after so it will never be successful.
- It shouldn't contain more than just the command line for tht executable, so that `cd` command shouldn't be in there.
- it hardcodes the path for the executable, ignore any possible prefix, etc. Ideally it would be just in a standard location.

https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

I'd submit a patch, but the CMake system link an executable `filmulator` that is installed in `$PREFIX/bin` (that's good), but is inconsistent with the qmake build system. So the matters are a bit more complicated.

**Comment by hfiguiere** [comment]
The warnings by flatpak-builder (as it runs `desktop-file-validate`)

```
WARNING: Failed to validate desktop file /home/hub/source/org.filmulator.Filmulator/repo/export/share/applications/org.filmulator.Filmulator.desktop: /home/hub/source/org.filmulator.Filmulator/repo/export/share/applications/org.filmulator.Filmulator.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
/home/hub/source/org.filmulator.Filmulator/repo/export/share/applications/org.filmulator.Filmulator.desktop: error: value "cd/usr/lib/filmulator-gui && /usr/lib/filmulator-gui/filmulator-gui" for key "Exec" in group "Desktop Entry" contains a reserved character '&' outside of a quote
/home/hub/source/org.filmulator.Filmulator/repo/export/share/applications/org.filmulator.Filmulator.desktop: error: value "cd/usr/lib/filmulator-gui && /usr/lib/filmulator-gui/filmulator-gui" for key "Exec" in group "Desktop Entry" contains a reserved character '&' outside of a quote

WARNING: Binary not found for Exec line in /home/hub/source/org.filmulator.Filmulator/repo/export/share/applications/org.filmulator.Filmulator.desktop: cd/usr/lib/filmulator-gui && /usr/lib/filmulator-gui/filmulator-gui
```

**Comment by CarVac** [comment]
I'd rather make this compatible with cmake.
