### ISSUE TITLE
Request: Fixed Aspect Ratio for Cropping

### ISSUE THREAD

**Issue by akloster** [CarVac/filmulator-gui#133]
So far I've mostly used Dark Table for my photos and as a final step of my workflow I crop the picture. Darktable offers both unconstrained cropping and a selection of common aspect ratios. Most of the time I want to export for a certain Forum, Facebook, Instagram or even printing, and such a feature would be useful.

Also more options for saving/exporting. Most of the time my photos are taken at a much higher resolution than I can post, so they need to be scaled down. Filmulator doesn't do that right now.

Thank you for your time and hard work on Filmulator!

**Comment by CarVac** [comment]
If you hold shift while dragging a corner of the crop, it will snap to the nearest common aspect ratio in either portrait or landscape orientation. From memory, there's 1:1, 5:4, 4:3: 3:2, golden ratio, 16:9: 2:1, 2.35:1, and maybe a few higher than those.

Once you've found an aspect ratio you like, hold ctrl (and perhaps release shift) to lock in that aspect ratio.

Changing output resolution is going to be possible in the near future.
