### ISSUE TITLE
[Question]: filmulator-cli availability?

### ISSUE THREAD

**Issue by yrgim** [CarVac/filmulator-gui#136]
Hi,

I'm interested in how diffusion and crystal growth models are implemented. 
As a newbie programmer with nearly zero experience with cpp.

After looking around repo, it seems original 'filmulator' was written by "Omer Mano and Carlo Vaccari".
Is there any source code of original filmulator? with Makefile, or build instructions.

Thanks in advance,

**Comment by yrgim** [comment]
Is this original command-line application? https://github.com/mermerico/filmulator

**Comment by CarVac** [comment]
Yes, that's the original. It's significantly slower and doesn't have nearly the features of the current pipeline, such as the tone controls after the film simulation (I used to use RawTherapee to do post-Filmulation edits), or the ability to change white balance, or lens corrections.

**Comment by yrgim** [comment]
Thanks for response!
