### ISSUE TITLE
Halo reduction

### ISSUE THREAD

**Issue by mbetrifork** [CarVac/filmulator-gui#137]
I've been trying out Filmulator for a while now, getting to really understand what the controls do and how I can use the program the way it was intended.

I really, really like the simplicity of the gui, and the whole process is very intuitive. It takes very little effort to get a very good result, and the colors always seem to turn out better. A red rose stays a red rose and never turns into a purple rose.

I get that the program was created with film development in mind, and I'm more than willing to take the good with the bad in that respect. However, there is one thing that is kind of a showstopper for me, unfortunately.

The Drama slider creates what looks like a low pass filter with a specific size, which is then used to boost shadow detail and reduce highlights. It might not work exactly like that but I think that's what happens. In areas with high contrast - like trees or buildings against a light sky, increasing Drama creates a halo effect which is very, very visible.

I realize this may be just another part of the underlying "film development" principles. So - a feature, not a bug. However, regardless of what the intent was, objectively the effect is just distracting. Sometimes very much so.

There are techniques you can use to reduce or avoid halos entirely. The low pass filter could be combined with a threshold, or the drama slider could just be more intelligent about how it applies an effect in areas that already have high contrast.

So as a feature request I would like to ask for "some way" to reduce halos.

**Comment by CarVac** [comment]
The way to reduce halos is to reduce the film area slider to spread out the halo over a larger area until the eye stops noticing it.

The default film area is good for the default drama in most cases, but as you strengthen the effect you need
