### ISSUE TITLE
Dodging and burning

### ISSUE THREAD

**Issue by mbetrifork** [CarVac/filmulator-gui#138]
Hello - just an idea. Part of the old darkroom film process was the ability to brighten dark areas and darken bright areas. Wikipedia is our friend here:

https://en.wikipedia.org/wiki/Dodging_and_burning

As a film development simulator, it would be amazing if we could have some way to emulate this process as well. I have no suggestions on how this might be achieved in the GUI but it might be in the form of a brush or some other way to apply a mask which is then "exposed" more.

**Comment by CarVac** [comment]
This is not something I'm planning on including in Filmulator for simplicity reasons… but I may reconsider in the long term if I feel like I have a handle on a good UI for it.
