### ISSUE TITLE
Unsharp masking

### ISSUE THREAD

**Issue by mbetrifork** [CarVac/filmulator-gui#139]
Hi,

Another old darkroom technique is the process of unsharp masking, to improve percieved image sharpness. See this Wikipedia article, under "Photographic darkroom unsharp masking": https://en.wikipedia.org/wiki/Unsharp_masking

I think some form of sharpening would be great, since the result from Filmulator always requires sharpening after development. I use Darktable's high pass module combined with its sharpening module to further sharpen the midtones, but in relation to Filmulator, to stay true to the original idea, I think simple unsharp masking following the principles of Darkroom development would be more than adequate for most.

**Comment by CarVac** [comment]
I would disagree that the result from Filmulator always requires sharpening, but I have sharp lenses and not such high resolution cameras.

One of the RawTherapee developers is planning on porting its Capture Sharpening to librtprocess. From there I can include it in Filmulator. This is a module that automatically detects and sharpens away lens softness without overshoot, as I understand it.

I may also add unsharp masking to a future output tab, as a post resize operation.

**Comment by CarVac** [comment]
Also see #12.

**Comment by mbetrifork** [comment]
Thanks for the follow up. I understand that lens sharpness is a factor and I also agree that not all images need sharpening, but some do and this is especially evident from the comparisons I've been doing lately, where I process the same images with Filmulator and then with Capture One. C1 does sharpen things up a bit by default and the results are usually more pleasing than not. So I thought it would be a useful addition - especially if implemented using the film metafor with unsharp masking.

Interesting idea with the Capture Sharpening. This would be a great addition although of course not so "film like" (there would be no darkroom equivalent of that process). Still, it's the results that matter.

**Comment by CarVac** [comment]
I'm not so stuck on doing things the filmlike way if it's not better than other processes.

I created the film-based tonemapping because I felt like that was a better way to compress dynamic range and enhance colors and contrast, not because of I'm trying to do everything like film.

Perhaps dodging and burning based on film would be better than what you can find in GIMP (which always feels unintuitive to me compared to the real deal) so eventually I may implement it.
