### ISSUE TITLE
Pregenerated PNG icon is non-square

### ISSUE THREAD

**Issue by danfe** [CarVac/filmulator-gui#147]
The `resources/filmulator64icon.png` file has size 64x58 which Qt (tested with 5.15.2 but may affect any version) apparently does not accept as a valid icon, so the call to `window->setIcon(QIcon(...))` in `main.cpp` is useless.  Converting (or using instead of PNG) original SVG file to proper 64x64 sized icon fixes the problem.

**Comment by CarVac** [comment]
Huh, I didn't consider that the original SVG might work; I'll test that on the platforms I have available.

The non-square PNG works on Linux and Windows, for what it's worth.

**Comment by CarVac** [comment]
SVG works on my Linux machine, and plays slightly better with the KDE taskbar than the PNG did. I'll test the Windows build after work.

**Comment by danfe** [comment]
> Huh, I didn't consider that the original SVG might work

Qt documentation [states](https://doc.qt.io/qt-5/qicon.html) that it has SVG support in the icon engine since Qt 4.2.

**Comment by CarVac** [comment]
The SVG change works on both Windows and Linux, so I'm considering this issue fixed.

What platform were you having the issue on, btw?

**Comment by danfe** [comment]
> What platform were you having the issue on, btw?

I'm on FreeBSD/amd64.  Since you've added the `.svg` icon to `resources/pixmaps.qrc`, shouldn't the `.png` version be removed to trim 4KB off the executable size?

**Comment by CarVac** [comment]
Good idea, done.

**Comment by CarVac** [comment]
Hm, this broke the Linux AppImage icon. I didn't expect that to be different from the locally built one...
