### ISSUE TITLE
Fujifilm RAF: some pictures randomly come out as entirely blue

### ISSUE THREAD

**Issue by jcelerier** [CarVac/filmulator-gui#150]
Consider these files: https://we.tl/t-2tpiqVT06x 

DSF0876 comes out normally, but DSF0877 (taken just after, no setting change) is entirely blue: 

![bleu](https://user-images.githubusercontent.com/2772730/217661947-96dd4bcf-4a4a-42dc-a3e1-b4d1e88dd3e8.png)

it shows up fine in Dolphin (file manager) and Darktable ; you can see in my pics in the bottom that many are just randomly blue. ISO, etc are the same.

**Comment by johnmaguire** [comment]
@jcelerier The WB is set around 2000 which is pretty cool. Could this be a WB issue?

P.S. the download link no longer works.

**Comment by CarVac** [comment]
It was already fixed in the development builds.

I just need to actually release it…
