### ISSUE TITLE
Feature request: See all images without needing to find them in the calendar

### ISSUE THREAD

**Issue by Beep6581** [CarVac/filmulator-gui#38]
I would like to see all imported images without needing to hunt them down in the calendar.

**Comment by CarVac** [comment]
1. Are you on the dateHistogram branch? It shows a histogram of how many photos you've taken on each day, making it easier to find when you've shot.

2. I'm planning on adding a view in last-imported order to the Import tab; that's probably what you're looking for here.

**Comment by Beep6581** [comment]
I'm on master.

A view which shows all imported photos in order of import date would be fine, though issue #37 would be better,

**Comment by CarVac** [comment]
Try the dateHistogram branch, it has a bunch of bugfixes and other features in addition to the date histogram itself.

(I should probably just merge it into master though)

**Comment by CarVac** [comment]
Have you tried the latest version on master?

**Comment by Beep6581** [comment]
Not yet, I won't have time to test for a while.

**Comment by CarVac** [comment]
Progress has been made on putting a most-recently-imported view on the Import tab.

**Comment by CarVac** [comment]
You can select a range of dates in the date histogram now.
