### ISSUE TITLE
macstack: .ORF import causing crash when importing

### ISSUE THREAD

**Issue by Benitoite** [CarVac/filmulator-gui#74]
Olympus format causing a crash, perhaps another example of [LibRaw hitting the top of stack.](
https://www.libraw.org/comment/4774#comment-4774)
Example crashing ORF https://raw.pixls.us/getfile.php/2785/nice/Olympus%20-%20E-M10%20Mark%20II%20-%2016bit%20(4:3).ORF

From the console:
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

libc++abi.dylib: terminating with uncaught exception of type Exiv2::BasicError<char>: tiff directory length is too large
Abort trap: 6

```

**Comment by waxfingers** [comment]
I can reproduce, macos 10.14

**Comment by CarVac** [comment]
It's not a stack issue, it's an EXIF issue.

Right now, Filmulator just naively copies the whole EXIF from the source file to the destination file; sometimes this causes issues, especially with DNGs.

**Comment by Benitoite** [comment]
Duplicates #70
