### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by signalwerk** [CarVac/filmulator-gui#90]
I made a first draft to bring a website online. Right now it's a static website hosted by github. I built it with a static site generator. I'm not 100% convinced about the one I used, but it would be good to have a system to easily write text (Markdown) and have Interaction in that Text (JS-Components). With `.mdx` thats possible. 

I setup a [repo](https://github.com/signalwerk/filmulator-web/) and everything is in early draft.

Here my request:
Could you @CarVac upload your presentation-file of Libre Graphics Meeting here. Then I could take out some context for a first start-site and you could then probably have a look at it and bring in your ideas.

Would that be of interest for you?

**Comment by CarVac** [comment]
I'll upload it when I get the chance.

I prefer that it be in the same repo as the main code so I can keep the website in sync with changes to the application: the website would reflect what

**Comment by signalwerk** [comment]
@CarVac what do you mean by `sync`? Is there a auto-documentation out of the source?

**Comment by CarVac** [comment]
Currently every time I make a release I edit the Github wiki for all the new features.

If I can document them as I add them that would be great.

**Comment by CarVac** [comment]
(I didn't mean to close the issue yesterday. I fat-fingered the comment button on mobile)

**Comment by signalwerk** [comment]
oh wow... I didn't know/see the wiki-pages. Awesome! Thats a great start!

The Structure for a start of the website could be something like:

* Start-Page · Overview/Features → LGM–Presentation as Basis
* Introduction · Wiki: Basic guide to the User Interface
* Processing · Wiki: Basic guide to Photo Processing

I think it would be nice to have a website for the program to gain more users/contributors, since I think the Program is well thought trough. But if it's in a separate repo or not is up to you. The main thing for me is that you can easily adapt it with Markdown (mdx) and it gets built with travis then. so it's no hassle to update it.

**Comment by CarVac** [comment]
I guess even if it's in a separate repo, I could just keep parallel branches (it would take a small amount of discipline, I suppose).

**Comment by signalwerk** [comment]
@CarVac sure since it's git whoever wanna PR or branch can work on it. I usually also do something like «Found a typo or wanna improve this site? Pull Requests are always welcome» in the footer. With the link to the source-file. So it's easy for people to contribute.

**Comment by CarVac** [comment]
https://filmulator.org is the new website.
