### ISSUE TITLE
find_package(Exiv2 0.25 REQUIRED) not working on mac

### ISSUE THREAD

**Issue by Benitoite** [CarVac/filmulator-gui#96]
@CarVac @cryptomilk etc.

https://github.com/CarVac/filmulator-gui/blob/927375ad5cebb82da9fb3e80ffe6c229134e362b/filmulator-gui/CMakeLists.txt#L27

For me, using Exiv2.27.1, if you spell it `EXIV2` instead of `Exiv2`, it works.  
As `Exiv2`, it reports the version as `".."` and fails:
```
-- Checking for module 'exiv2'
--   Found exiv2, version 0.27.1
CMake Error at /opt/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Exiv2: Found unsuitable version "..", but required is at
  least "0.25" (found /opt/local/include)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindExiv2.cmake:83 (find_package_handle_standard_args)
  CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by CarVac** [comment]
For me, if I use `find_package(EXIV2 0.25 REQUIRED)`, then I need to rename `filmulator-gui/cmake/Modules/FindExiv2.cmake` to `FindEXIV2.cmake`.

Does that work for you?

**Comment by Benitoite** [comment]
Spelling of the cmake module filename works either way. 
It also works if I spell `exiv2` on line 27 https://github.com/CarVac/filmulator-gui/blob/927375ad5cebb82da9fb3e80ffe6c229134e362b/filmulator-gui/CMakeLists.txt#L27
